### ISSUE TITLE
Changes made to the api is crashing our systems

### ISSUE THREAD

**Issue by praveenapoojary** [mongoose-os-libs/dash#1]
I developed a python script to prepare the device for production using one command. Python script connects the device to azure and mongoose dashboard.
I am using `https://dash.mongoose-os.com/api/v2/devices` this API to post new device to the dashboard and sending parameters like this `{"name": "10000002", "id": "10000002"}`.
Before posting new device I first try to get the details of the device  using  `https://dash.mongoose-os.com/api/v2/devices/:id` if I am able to get detail means device already exists so I don't allow post API in my script so that we can stop accidental overwrite but from last week your team changed the API where if I post any device id parameter is not getting considered and you are generating your own id.  Please tell us how to tackle this.

**Comment by cpq** [comment]
Correct, from now on the device creation does accepts an empty payload only.
You can't change the ID. You can change the name, shared_with, and the shadow.
