### ISSUE TITLE
Use  !== instead of !=

### ISSUE THREAD

**Issue by tripflex** [mongoose-os-libs/dash#2]
https://github.com/mongoose-os-libs/dash/blob/ddeaca6d207f5513ee288240a01fed101e0d3f23/mjs_fs/api_dash.js#L18

**Comment by kogitant** [comment]
Same issue here with esp32 trying to send data to dash with Dash.notify

**Comment by nliviu** [comment]
Fixed https://github.com/mongoose-os-libs/dash/commit/3a81cf610c67c66033b4227ed4c8c31fd69582d9
